name = "ztyblog"
license = "MIT"
licenselink = "https://github.com/zhengzangw/hugo-theme-ztyblog/blob/master/LICENSE"
description = "A full-featured theme for Hugo. All in one."
homepage = "https://github.com/zhengzangw/hugo-theme-ztyblog"
tags = ["blog"]
features = ["blog"]
min_version = 0.60

[[author]]
  name = "Zangwei Zheng"
  homepage="https://github.com/zhengzangw/"
[[author]]
  name = "Tianyun Zhang"
  homepage="https://github.com/doowzs/"
